# prometheus-kube-prometheus-stack-prometheus-db-prometheus-kube-prometheus-stack-prometheus-0 is not valid YAML, this value comes from alerts.tf. Ignoring this so the pint part of the pipeline doesn't fail due to invalid syntax.
# pint ignore/begin
groups:
  - name: prometheus-extended.rules
    rules:
      - alert: PrometheusStorageLow
        annotations:
          message: 'Prometheus storage has {{ printf "%.2f" $$value }}% capacity remaining.'
          runbook: "https://aurora.gccloudone.ca/en/documentation/monitoring-surveillance/prometheus/cluster-alert-runbooks/prometheus-storage-low/#resolution-process"
        expr: 'sum by (persistentvolumeclaim, namespace, node)  (kubelet_volume_stats_available_bytes{persistentvolumeclaim="prometheus-kube-prometheus-stack-prometheus-db-prometheus-kube-prometheus-stack-prometheus-0"} / kubelet_volume_stats_capacity_bytes{persistentvolumeclaim="prometheus-kube-prometheus-stack-prometheus-db-prometheus-kube-prometheus-stack-prometheus-0"}) * 100 < 15'
        for: 15m
        labels:
          scope: cluster
          severity: P2-Major
      - alert: PrometheusDiskMayFillIn60Hours
        annotations:
          message: 'Prometheus storage is predicted to have {{ printf "%.2f" $$value }}% capacity remaining 60 hours from now and will run out of space soon.'
          runbook: "https://aurora.gccloudone.ca/en/documentation/monitoring-surveillance/prometheus/cluster-alert-runbooks/prometheus-storage-low/#resolution-process"
        expr: 'sum by (persistentvolumeclaim, namespace, node) ((predict_linear(kubelet_volume_stats_available_bytes{persistentvolumeclaim="prometheus-kube-prometheus-stack-prometheus-db-prometheus-kube-prometheus-stack-prometheus-0"}[7d], 60 * 3600)) / kubelet_volume_stats_capacity_bytes{persistentvolumeclaim="prometheus-kube-prometheus-stack-prometheus-db-prometheus-kube-prometheus-stack-prometheus-0"} * 100 < 10)'
        for: 30m
        labels:
            scope: cluster
            severity: P1-Critical
      - alert: AlertmanagerFailedNotification
        annotations:
          summary: 'Alertmanager is failing to send notification.'
          message: 'Alertmanager {{ $$labels.namespace }}/{{ $$labels.pod }} failed to send {{ $$value | humanizePercentage }} of notifications to the {{ $$labels.integration }} integration'
        expr: |
          # Added exclusion for email and webhook due to them being to noisy, should be added back when alerts are fixed
          (
            rate(
              alertmanager_notifications_failed_total{
                namespace="prometheus-system",
                integration!~"email|webhook"
              }[5m]
            )
            /
            ignoring (reason) group_left
            rate(
              alertmanager_notifications_total{
                namespace="prometheus-system",
                integration!~"email|webhook"
              }[5m]
            )
          ) > 0.01
        for: 5m
        labels:
          scope: cluster
          severity: P2-Major
          teams_version: v2
      - alert: PrometheusRuleFailure
        annotations:
          summary: 'Prometheus is failing rule evaluation.'
          message: 'Prometheus {{ $$labels.namespace }}/{{ $$labels.pod }} failed to evaluate {{ printf "%.0f" $$value }} rules in the last 5 mins'
        expr: |
          increase(
            prometheus_rule_evaluation_failures_total{
              namespace="prometheus-system"
              }[5m]
          ) > 0 
        for: 15m
        labels:
          scope: cluster
          severity: P2-Major
          teams_version: v2
      - alert: PrometheusTargetsDown
        annotations:
          summary: 'Prometheus scrape targets down'
          message: '{{ printf "%.1f" $$value }}% of targets for job {{ $$labels.job }} down in the last 15 mins'
        expr: |
          100 *
          (
            count by (job, namespace, service) (up == 0)
            /
            count by (job, namespace, service) (up)
          ) > 10
        for: 15m
        labels:
          scope: cluster
          severity: P2-Major
          teams_version: v2
#
#
# pint ignore/end
