{{ if .Values.components.trustManager.enabled -}}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ .Values.global.cluster }}-trust-manager-bundle"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.global.project }}
  source:
    chart: {{ .Values.global.raw.helm.chart }}
    repoURL: {{ default .Values.global.helm.repository .Values.global.raw.helm.repository }}
    targetRevision: {{ .Values.global.raw.helm.targetRevision }}
    helm:
      releaseName: "trust-manager-bundle"
      values: |
        resources:
          - apiVersion: trust-manager.io/v1
            kind: Bundle
            metadata:
              name: trust-manager-propagated-custom-ca
              labels:
                app.kubernetes.io/name: "trust-manager-bundle"
                app.kubernetes.io/instance: "{{ .Values.global.cluster }}"
                app.kubernetes.io/component: config
                app.kubernetes.io/part-of: trust-manager-system
                app.kubernetes.io/managed-by: argo
                helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version }}
            spec:
              sources:
                - useDefaultCAs: true
                {{ if .Values.components.trustManager.bundle.customCA }}
                - inLine: |
                    {{ .Values.components.trustManager.bundle.customCA }}
                {{ end }}
              target:
                configMap:
                  key: "custom.crt"
                namespaceSelector:
                  matchLabels:
                    namespace.ssc-spc.gc.ca/trust-manager: active
  destination:
    name: {{ .Values.global.cluster }}
    namespace: platform-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

{{- end }}
