{{ if .Values.components.trustManager.enabled -}}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ .Values.global.cluster }}-trust-manager-netpol"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.global.project }}
  source:
    chart: {{ .Values.global.raw.helm.chart }}
    repoURL: {{ default .Values.global.helm.repository .Values.global.raw.helm.repository }}
    targetRevision: {{ .Values.global.raw.helm.targetRevision }}
    helm:
      releaseName: trust-manager-netpol
      values: |
        resources:
          - apiVersion: networking.k8s.io/v1
            kind: NetworkPolicy
            metadata:
              name: allow-same-namespace
              namespace: trust-manager-system
            spec:
              podSelector: {}
              policyTypes:
                - Ingress
                - Egress
              ingress:
                - from:
                  - podSelector: {}
              egress:
                - to:
                  - podSelector: {}
          - apiVersion: networking.k8s.io/v1
            kind: NetworkPolicy
            metadata:
              name: allow-ingress-from-cert-manager-to-trust-manager
              namespace: trust-manager-system
            spec:
              ingress:
              - from:
                - namespaceSelector:
                    matchLabels:
                      namespace.ssc-spc.gc.ca/purpose: system
                      kubernetes.io/metadata.name: cert-manager-system
                  podSelector:
                    matchLabels:
                      app.kubernetes.io/name: cert-manager
              podSelector:
                matchLabels:
                  app.kubernetes.io/name: trust-manager
              policyTypes:
                - Ingress
          - apiVersion: networking.k8s.io/v1
            kind: NetworkPolicy
            metadata:
              name: allow-egress-to-cert-manager-from-trust-manager
              namespace: trust-manager-system
            spec:
              egress:
                - to:
                  - namespaceSelector:
                      matchLabels:
                        namespace.ssc-spc.gc.ca/purpose: system
                        kubernetes.io/metadata.name: cert-manager-system
                    podSelector:
                      matchLabels:
                        app.kubernetes.io/name: cert-manager
              podSelector:
                matchLabels:
                  app.kubernetes.io/name: trust-manager
              policyTypes:
              - Egress
  destination:
    name: {{ .Values.global.cluster }}
    namespace: platform-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

{{- end }}
