groups:
- name: trivy.rules
  rules:
  - alert: TrivyCriticalVulnerabilitiesDetected
    expr: 'sum by (namespace, image_repository, image_tag) (trivy_image_vulnerabilities{severity="Critical", image_registry!~"mcr\\.microsoft\\.com|.*\\.azurecr\\.io|.*\\.amazonaws\\.com|gcr\\.io"} * on (namespace) group_left() kube_namespace_labels{label_namespace_ssc_spc_gc_ca_purpose="system"}) > 0'
    for: 5m
    labels:
      severity: P1-Critical
      scope: cluster
      teams_version: v2
    annotations:
      message: 'Image {{ $$labels.image_repository }}:{{ $$labels.image_tag }} has {{ $$value }} critical vulnerabilities.'