{{- if eq .Values.namespace.type "argocd-control-plane" }}

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-control-plane-multi-tenant
  namespace: {{ $.Release.Name }}
rules:
- apiGroups:
  - argoproj.io
  resources:
  - applications
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-control-plane-multi-tenant
  namespace: {{ $.Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-control-plane-multi-tenant
{{- if .Values.rbac.groups }}
subjects:
{{- range .Values.rbac.groups }}
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: "{{ . }}"
{{- end }}
{{- else }}
subjects: []
{{- end }}

{{- end }}
