{{ if .Values.components.grafana.enabled -}}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ .Values.global.cluster }}-grafana-resources"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.global.project }}
  source:
    chart: {{ .Values.global.raw.helm.chart }}
    repoURL: {{ default .Values.global.helm.repository .Values.global.raw.helm.repository }}
    targetRevision: {{ .Values.global.raw.helm.targetRevision }}
    plugin:
      env:
        - name: HELM_RELEASE_NAME
          value: "grafana-resources"
        - name: HELM_VALUES
          value: |
            resources:
              - apiVersion: grafana.integreatly.org/v1beta1
                kind: Grafana
                metadata:
                  name: grafana
                  namespace: grafana-system
                  labels:
                    dashboards: "aurora"
                spec:
    
                  persistentVolumeClaim:
                    spec:
                      accessModes:
                        - ReadWriteOnce
                      storageClassName: default
                      resources:
                        requests:
                          storage: 20Gi
                  
                  config:
                    auth.anonymous:
                      enabled: "false"
                    analytics:
                      check_for_updates: "false"
                      reporting_enabled: "false"
                    metrics:
                      enabled: "true"
                    plugins:
                      plugins_update_checker: "false"
                    security:
                      adminPassword: {{ required "grafana.adminPassword is required" .Values.components.grafana.adminPassword | quote }}
                    server:
                      root_url: {{ .Values.components.grafana.serverUrl | default (printf "http://localhost:3000/login/azuread" .Values.components.grafana.serverUrl) | quote }}
                    {{- if eq .Values.global.provider "azure" }}
                    auth.azuread:
                      enabled: "true"
                      name: "Azure AD"
                      allow_sign_up: "true"
                      client_id: "$$__file{/etc/secrets/auth_azuread/client_id}"
                      client_secret: "$$__file{/etc/secrets/auth_azuread/client_secret}"
                      scopes: "openid email profile"
                      auth_url: {{ .Values.components.grafana.authUrl | default (printf "https://microsoftonline.com" .Values.global.tenantId) | quote }}
                      token_url: {{ .Values.components.grafana.tokenUrl | default (printf "https://microsoftonline.com" .Values.global.tenantId) | quote }}
                      allowed_domains: ""
                      allowed_groups: {{ .Values.components.grafana.allowedGroups | quote }}
                      role_attribute_strict: "false"
                      role_attribute_path: "contains(roles[*], 'grafana-admin') && 'Admin' || 'Viewer'"
                      {{- end }}
    
                  service:
                    metadata:
                      labels:
                        app.kubernetes.io/name: grafana
                        app.kubernetes.io/instance: grafana
                        app.kubernetes.io/component: grafana
                    spec:
                      ports:
                        - name: grafana
                          port: 3000
                          protocol: TCP
                          targetPort: 3000
    
                  deployment:
                    spec:
                      strategy:
                        type: Recreate
                      template:
                        spec:
                          securityContext:
                            runAsNonRoot: true
                            runAsUser: 10000
                            runAsGroup: 10000
                            fsGroup: 10000
                            seccompProfile:
                              type: RuntimeDefault
                          priorityClassName: platform-cluster-critical
                          nodeSelector:
                            kubernetes.io/os: linux
                            node.ssc-spc.gc.ca/purpose: system
                          tolerations:
                            - key: CriticalAddonsOnly
                              operator: Exists
                          
                          volumes:
                            - name: grafana-storage
                              persistentVolumeClaim:
                                claimName: grafana-pvc
                            {{- if eq .Values.global.provider "azure" }}
                            - name: auth-azuread-oauth-secret-mount
                              secret:
                                secretName: auth-azuread-oauth-secret
                                defaultMode: 288
                            {{- end }}
                            - name: trust-manager-custom-ca
                              configMap:
                                name: trust-manager-propagated-custom-ca
    
                          containers:
                            - name: grafana
                              image: "{{ default "docker.io" .Values.global.container.registry }}/grafana/grafana:13.1.0"
                              env:
                                - name: GF_PLUGINS_PREINSTALL
                                  value: ""
                              resources:
                                limits:
                                  cpu: 500m
                                  memory: 500M
                                requests:
                                  cpu: 100m
                                  memory: 100M
                              volumeMounts:
                                - name: grafana-storage
                                  mountPath: /var/lib/grafana
                               {{- if eq .Values.global.provider "azure" }}
                                - name: auth-azuread-oauth-secret-mount
                                  mountPath: /etc/secrets/auth_azuread
                                  readOnly: true
                                {{- end }}
                                - name: trust-manager-custom-ca
                                  mountPath: /etc/ssl/certs/ca-certificates.crt
                                  subPath: ca-certificates.crt
                                  readOnly: true
    
              - apiVersion: monitoring.coreos.com/v1
                kind: ServiceMonitor
                metadata:
                  name: grafana
                  namespace: grafana-system
                spec:
                  endpoints:
                    - interval: 30s
                      path: /metrics
                      port: grafana
                  selector:
                    matchLabels:
                        app.kubernetes.io/name: grafana
                        app.kubernetes.io/instance: grafana
                        app.kubernetes.io/component: grafana

  destination:
    name: {{ .Values.global.cluster }}
    namespace: grafana-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

{{- end }}
