{{ if .Values.components.grafana.enabled -}}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ .Values.global.cluster }}-grafana-datasource-resources"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.global.project }}
  source:
    chart: {{ .Values.global.raw.helm.chart }}
    repoURL: {{ default .Values.global.helm.repository .Values.global.raw.helm.repository }}
    targetRevision: {{ .Values.global.raw.helm.targetRevision }}
    helm:
      releaseName: grafana-datasource-resources
      values: |
        resources:
          - apiVersion: grafana.integreatly.org/v1beta1
            kind: GrafanaDatasource
            metadata:
              name: aurora-prometheus-source
              namespace: grafana-system
            spec:
              instanceSelector:
                matchLabels:
                  dashboards: "aurora"
              datasource:
                name: Prometheus
                type: prometheus
                uid: prometheus
                url: http://kube-prometheus-stack-prometheus.prometheus-system:9090/
                access: proxy
                isDefault: true
                jsonData:
                  httpMethod: POST
                  timeInterval: 30s
          {{- if .Values.components.thanos.enabled }}
          # This is a non-default datasource pointing at the Thanos Querier.
          # Purpose: long-term (Blob) data can be queried without touching the primary datasource.
          # The Querier is a drop-in PromQL endpoint, grafana can point to this datasource if we wish to
          - apiVersion: grafana.integreatly.org/v1beta1
            kind: GrafanaDatasource
            metadata:
              name: aurora-thanos-source
              namespace: grafana-system
            spec:
              instanceSelector:
                matchLabels:
                  dashboards: "aurora"
              datasource:
                name: Thanos
                type: prometheus
                uid: thanos
                url: http://thanos-query.prometheus-system:9090/
                access: proxy
                isDefault: false
                jsonData:
                  httpMethod: POST
                  timeInterval: 30s
          {{- end }}

  destination:
    name: {{ .Values.global.cluster }}
    namespace: grafana-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

{{- end }}
