{{ if and .Values.components.grafana.enabled (eq .Values.global.provider "azure") -}}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ .Values.global.cluster }}-grafana-ad-secret"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.global.project }}
  source:
    chart: {{ .Values.global.raw.helm.chart }}
    repoURL: {{ default .Values.global.helm.repository .Values.global.raw.helm.repository }}
    targetRevision: {{ .Values.global.raw.helm.targetRevision }}
    plugin:
      env:
        - name: HELM_RELEASE_NAME
          value: "grafana-ad-secret"
        - name: HELM_VALUES
          value: |
            resources:
              - apiVersion: v1
                kind: Secret
                metadata:
                  name: auth-azuread-oauth-secret
                  namespace: grafana-system
                  labels:
                    app.kubernetes.io/name: "grafana-ad-secret"
                    app.kubernetes.io/instance: "{{ .Values.global.cluster }}"
                    app.kubernetes.io/component: auth
                    app.kubernetes.io/part-of: grafana-system
                    app.kubernetes.io/managed-by: argo
                stringData:
                  client_id: {{ required "grafana.azure.clientId is required" .Values.components.grafana.azure.clientId | quote }}
                  client_secret: {{ required "grafana.azure.clientPassword is required" .Values.components.grafana.azure.clientPassword | quote }}
                type: Opaque

  destination:
    name: {{ .Values.global.cluster }}
    namespace: grafana-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

{{- end }}
