{{ if .Values.components.grafana.enabled -}}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ .Values.global.cluster }}-grafana-operator"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.global.project }}
  source:
    chart: {{ default "grafana-operator" .Values.components.grafana.helm.chart }}
    {{- if .Values.components.grafana.helm.repository}}
    repoURL: {{ .Values.components.grafana.helm.repository }}
    {{- else }}
    repoURL: {{ default "ghcr.io/grafana/helm-charts" .Values.global.helm.repository }}
    {{- end }}
    targetRevision: {{ .Values.components.grafana.helm.targetRevision }}
    plugin:
      env:
        - name: HELM_RELEASE_NAME
          value: "grafana-operator"
        - name: HELM_VALUES
          value: |
            global:
              imageRegistry: {{ default "ghcr.io" .Values.global.container.registry }}

            podSecurityContext:
              runAsNonRoot: true
              runAsUser: 10000
              seccompProfile:
                type: RuntimeDefault

            image: {{ default "{}" (include "grafana-operator.image" .) | nindent 14 }}

            resources: {{ toYaml .Values.components.grafana.resources | nindent 14 }}
            nodeSelector: {{ toYaml .Values.components.grafana.nodeSelector | nindent 14 }}
            tolerations: {{ toYaml .Values.components.grafana.tolerations | nindent 14 }}
            affinity: {{ toYaml .Values.components.grafana.affinity | nindent 14 }}
            priorityClassName: {{ .Values.components.grafana.priorityClassName }}

  destination:
    name: {{ .Values.global.cluster }}
    namespace: grafana-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

{{- end }}
