{{ if .Values.components.gatekeeper.enabled -}}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ .Values.global.cluster }}-gatekeeper-enforce-cbr"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    kubernetes.io/description: |
      Enforces that the CBR exists on a namespace.
spec:
  project: {{ .Values.global.project }}
  source:
    chart: {{ .Values.global.raw.helm.chart }}
    repoURL: {{ default .Values.global.helm.repository .Values.global.raw.helm.repository }}
    targetRevision: {{ .Values.global.raw.helm.targetRevision }}
    helm:
      releaseName: gatekeeper-enforce-cbr
      values: |
        resources:
          - apiVersion: constraints.gatekeeper.sh/v1beta1
            kind: MetadataRestrictions
            metadata:
              name: enforce-cbr
            spec:
              match:
                kinds:
                  - apiGroups:
                      - ''
                    kinds:
                      - Namespace
                excludedNamespaces: {{ toYaml .Values.components.gatekeeper.constraints.enforceCBR.excludedNamespaces | nindent 18 }}
              parameters:
                labels:
                  - allowedRegex: {{ .Values.components.gatekeeper.constraints.enforceCBR.allowedRegex | toYaml | nindent 20  }}
                    allowedValues: {{ .Values.components.gatekeeper.constraints.enforceCBR.allowedValues | toYaml | nindent 20 }}
                    key: finance.ssc-spc.gc.ca/workload-id
              enforcementAction: {{ .Values.components.gatekeeper.constraints.enforceCBR.enforcementAction }}
  destination:
    name: {{ .Values.global.cluster }}
    namespace: platform-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

{{- end }}
