{{- if eq .Values.global.provider "gcp" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ .Values.global.cluster }}-global-netpol"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.global.project }}
  source:
    chart: {{ .Values.global.raw.helm.chart }}
    repoURL: {{ default .Values.global.helm.repository .Values.global.raw.helm.repository }}
    targetRevision: {{ .Values.global.raw.helm.targetRevision }}
    helm:
      releaseName: global-netpol
      values: |
        resources:
          - apiVersion: cilium.io/v2
            kind: CiliumClusterwideNetworkPolicy
            metadata:
              name: dnscache-coredns-egress
            spec:
              endpointSelector:
                matchExpressions:
                  - key: io.kubernetes.pod.namespace
                    operator: NotIn
                    values:
                      - kube-system
              egress:
                - toEndpoints
                    - matchLabels:
                        k8s:k8s-app: kube-dns
                        k8s:io.kubernetes.pod.namespace: kube-system
                  toPorts:
                    - ports:
                        - port: "53"
                          protocol: UDP
                        - port: "53"
                          protocol: TCP
          - apiVersion: cilium.io/v2
            kind: CiliumClusterwideNetworkPolicy
            metadata:
              name: baseline-egress-cluster
            spec:
              endpointSelector:
                matchExpressions:
                  - key: io.kubernetes.pod.namespace
                    operator: NotIn
                    values:
                      - kube-system
              egress:
                - toEntities
                  - cluster
          - apiVersion: cilium.io/v2
            kind: CiliumClusterwideNetworkPolicy
            metadata:
              name: baseline-egress-gke-metadata
            spec:
              endpointSelector:
                matchExpressions:
                  - key: io.kubernetes.pod.namespace
                    operator: NotIn
                    values:
                      - kube-system
              egress:
                - toCIDR:
                    - 169.254.169.254/32
                  toPorts:
                    - ports:
                        - port: "988"
                          protocol: TCP
                - toCIDR:
                    - 169.254.169.254/32
                  toPorts:
                    - ports:
                        - port: "80"
                          protocol: TCP
  destination:
    name: {{ .Values.global.cluster }}
    namespace: platform-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end}}