# pint ignore/begin
groups:
  - name: alertmanager-extended.rules
    rules:
      - alert: AlertmanagerFailedNotification
        annotations:
          summary: 'Alertmanager is failing to send notification.'
          message: 'Alertmanager {{ $$labels.namespace }}/{{ $$labels.pod }} failed to send {{ $$value | humanizePercentage }} of notifications to the {{ $$labels.integration }} integration'
        expr: |
          # Added exclusion for email and webhook due to them being to noisy, should be added back when alerts are fixed
          (
            rate(
              alertmanager_notifications_failed_total{
                namespace="prometheus-system",
                integration!~"email|webhook"
              }[5m]
            )
            /
            ignoring (reason) group_left
            rate(
              alertmanager_notifications_total{
                namespace="prometheus-system",
                integration!~"email|webhook"
              }[5m]
            )
          ) > 0.01
        for: 5m
        labels:
          scope: cluster
          severity: P2-Major
          teams_version: v2
#
# pint ignore/end
