{
 "title": "Trivy Operator Dashboard",
 "description": "This Dashboard is used to visualise the metrics from the security reports of the Trivy Operator",
 "tags": [
  "trivy",
  "trivy operator",
  "security",
  "security scanning",
  "vulnerabilities"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Aurora Vulnerabilities",
   "type": "stat",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\r\n    max by (image_registry, image_repository, image_tag, severity) (\r\n        (trivy_image_vulnerabilities{severity=\"Critical\", image_registry!~\"mcr\\\\.microsoft\\\\.com|.*\\\\.azurecr\\\\.io|.*\\\\.amazonaws\\\\.com|gcr\\\\.io\"} > 0)\r\n        * on(namespace) group_left()\r\n        kube_namespace_labels{label_namespace_ssc_spc_gc_ca_purpose=\"system\"}\r\n    )\r\n) OR on() vector(0)",
     "legendFormat": "Critical"
    },
    {
     "expr": "sum(\r\n    max by (image_registry, image_repository, image_tag, severity) (\r\n        (trivy_image_vulnerabilities{severity=\"High\", image_registry!~\"mcr\\\\.microsoft\\\\.com|.*\\\\.azurecr\\\\.io|.*\\\\.amazonaws\\\\.com|gcr\\\\.io\"} > 0)\r\n        * on(namespace) group_left()\r\n        kube_namespace_labels{label_namespace_ssc_spc_gc_ca_purpose=\"system\"}\r\n    )\r\n) OR on() vector(0)",
     "legendFormat": "High"
    }
   ]
  },
  {
   "title": "CSP Vulnerabilities",
   "type": "stat",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\r\n    max by (image_registry, image_repository, image_tag, severity, namespace) (\r\n        trivy_image_vulnerabilities{severity=\"Critical\", image_registry=~\"mcr\\\\.microsoft\\\\.com|.*\\\\.azurecr\\\\.io|.*\\\\.amazonaws\\\\.com|gcr\\\\.io\"} > 0\r\n    )\r\n) OR on() vector(0)",
     "legendFormat": "Critical"
    },
    {
     "expr": "sum(\r\n    max by (image_registry, image_repository, image_tag, severity, namespace) (\r\n        trivy_image_vulnerabilities{severity=\"High\", image_registry=~\"mcr\\\\.microsoft\\\\.com|.*\\\\.azurecr\\\\.io|.*\\\\.amazonaws\\\\.com|gcr\\\\.io\"} > 0\r\n    )\r\n) OR on() vector(0)",
     "legendFormat": "High"
    }
   ]
  },
  {
   "title": "Client Vulnerabilities",
   "type": "stat",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\r\n    max by (image_registry, image_repository, image_tag, severity) (\r\n        (trivy_image_vulnerabilities{severity=\"Critical\"} > 0)\r\n        * on(namespace) group_left()\r\n        kube_namespace_labels{label_namespace_ssc_spc_gc_ca_purpose=\"solution\"}\r\n    )\r\n) OR on() vector(0)",
     "legendFormat": "Critical"
    },
    {
     "expr": "sum(\r\n    max by (image_registry, image_repository, image_tag, severity) (\r\n        (trivy_image_vulnerabilities{severity=\"High\"} > 0)\r\n        * on(namespace) group_left()\r\n        kube_namespace_labels{label_namespace_ssc_spc_gc_ca_purpose=\"solution\"}\r\n    )\r\n) OR on() vector(0)",
     "legendFormat": "High"
    }
   ]
  },
  { "title": "Vulnerabilities", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Top 10 SSC Image Vulnerabilities",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "topk(10,\r\n    sum by (image_repository, image_tag) (\r\n        max by (image_repository, image_tag, severity) (\r\n            trivy_image_vulnerabilities{image_registry!~\"mcr\\\\.microsoft\\\\.com|.*\\\\.azurecr\\\\.io|.*\\\\.amazonaws\\\\.com|gcr\\\\.io\"}\r\n            * on(namespace) group_left()\r\n            kube_namespace_labels{label_namespace_ssc_spc_gc_ca_purpose=\"system\"} \r\n        ) > 0\r\n    )\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (image_repository, image_tag) (\r\n    max by (image_repository, image_tag, severity) (\r\n        trivy_image_vulnerabilities{severity=\"Critical\", image_registry!~\"mcr\\\\.microsoft\\\\.com|.*\\\\.azurecr\\\\.io|.*\\\\.amazonaws\\\\.com|gcr\\\\.io\"}\r\n        * on(namespace) group_left()\r\n        kube_namespace_labels{label_namespace_ssc_spc_gc_ca_purpose=\"system\"} \r\n    ) > 0\r\n)\r\nand on (image_repository, image_tag)\r\ntopk(10,\r\n    sum by (image_repository, image_tag) (\r\n        max by (image_repository, image_tag, severity) (\r\n            trivy_image_vulnerabilities\r\n            * on(namespace) group_left()\r\n            kube_namespace_labels{label_namespace_ssc_spc_gc_ca_purpose=\"system\"} \r\n        ) > 0\r\n    )\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (image_repository, image_tag) (\r\n    max by (image_repository, image_tag, severity) (\r\n        trivy_image_vulnerabilities{severity=\"High\", image_registry!~\"mcr\\\\.microsoft\\\\.com|.*\\\\.azurecr\\\\.io|.*\\\\.amazonaws\\\\.com|gcr\\\\.io\"}\r\n        * on(namespace) group_left()\r\n        kube_namespace_labels{label_namespace_ssc_spc_gc_ca_purpose=\"system\"} \r\n    ) > 0\r\n)\r\nand on (image_repository, image_tag)\r\ntopk(10,\r\n    sum by (image_repository, image_tag) (\r\n        max by (image_repository, image_tag, severity) (\r\n            trivy_image_vulnerabilities\r\n            * on(namespace) group_left()\r\n            kube_namespace_labels{label_namespace_ssc_spc_gc_ca_purpose=\"system\"} \r\n        ) > 0\r\n    )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 Client Image Vulnerabilities",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "(\r\ntopk(10,\r\n    sum by (image_repository, image_tag) (\r\n        max by (image_repository, image_tag, severity) (\r\n            trivy_image_vulnerabilities\r\n            * on(namespace) group_left()\r\n            kube_namespace_labels{label_namespace_ssc_spc_gc_ca_purpose=\"solution\"} \r\n        ) > 0\r\n    )\r\n)\r\n)\r\nOR\r\nlabel_replace(label_replace(vector(0), \"image_repository\", \"no-client-images-found\", \"\", \"\"), \"image_tag\", \"none\", \"\", \"\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "(\r\nsum by (image_repository, image_tag) (\r\n    max by (image_repository, image_tag, severity) (\r\n        trivy_image_vulnerabilities{severity=\"Critical\"}\r\n        * on(namespace) group_left()\r\n        kube_namespace_labels{label_namespace_ssc_spc_gc_ca_purpose=\"solution\"} \r\n    ) > 0\r\n)\r\nand on (image_repository, image_tag)\r\ntopk(10,\r\n    sum by (image_repository, image_tag) (\r\n        max by (image_repository, image_tag, severity) (\r\n            trivy_image_vulnerabilities\r\n            * on(namespace) group_left()\r\n            kube_namespace_labels{label_namespace_ssc_spc_gc_ca_purpose=\"solution\"} \r\n        ) > 0\r\n    )\r\n)\r\n)\r\nOR\r\nlabel_replace(label_replace(vector(0), \"image_repository\", \"no-client-images-found\", \"\", \"\"), \"image_tag\", \"none\", \"\", \"\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "(\r\nsum by (image_repository, image_tag) (\r\n    max by (image_repository, image_tag, severity) (\r\n        trivy_image_vulnerabilities{severity=\"High\"}\r\n        * on(namespace) group_left()\r\n        kube_namespace_labels{label_namespace_ssc_spc_gc_ca_purpose=\"solution\"} \r\n    ) > 0\r\n)\r\nand on (image_repository, image_tag)\r\ntopk(10,\r\n    sum by (image_repository, image_tag) (\r\n        max by (image_repository, image_tag, severity) (\r\n            trivy_image_vulnerabilities\r\n            * on(namespace) group_left()\r\n            kube_namespace_labels{label_namespace_ssc_spc_gc_ca_purpose=\"solution\"} \r\n        ) > 0\r\n    )\r\n)\r\n)\r\nOR\r\nlabel_replace(label_replace(vector(0), \"image_repository\", \"no-client-images-found\", \"\", \"\"), \"image_tag\", \"none\", \"\", \"\")",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}