{{ if .Values.components.cilium.enabled -}}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ .Values.global.cluster }}-cilium-netpol"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.global.project }}
  source:
    chart: {{ .Values.global.raw.helm.chart }}
    repoURL: {{ default .Values.global.helm.repository .Values.global.raw.helm.repository }}
    targetRevision: {{ .Values.global.raw.helm.targetRevision }}
    helm:
      releaseName: cilium-netpol
      values: |
        resources:
          - apiVersion: networking.k8s.io/v1
            kind: NetworkPolicy
            metadata:
              name: allow-same-namespace
              namespace: cilium-system
            spec:
              podSelector: {}
              policyTypes:
                - Ingress
                - Egress
              ingress:
                - from:
                  - podSelector: {}
              egress:
                - to:
                  - podSelector: {}
          - apiVersion: networking.k8s.io/v1
            kind: NetworkPolicy
            metadata:
              name: allow-ingress-from-apiserver-to-cilium
              namespace: cilium-system
            spec:
              ingress:
              - from:
                - ipBlock:
                    cidr: {{ required "global.apiServerCidr is required" .Values.global.apiServerCidr | quote }}
                - namespaceSelector:
                    matchLabels:
                      kubernetes.io/metadata.name: kube-system
                  podSelector:
                    matchLabels:
                      app: konnectivity-agent
              podSelector:
                matchLabels: {}
              policyTypes:
              - Ingress
          - apiVersion: cilium.io/v2
            kind: CiliumNetworkPolicy
            metadata:
              name: allow-egress-from-hubble-relay-to-cilium-agents
              namespace: cilium-system
            spec:
              endpointSelector:
                matchLabels:
                  io.cilium.k8s.policy.serviceaccount: hubble-relay
              egress:
                - toEntities:
                  - host
                  - remote-node
          - apiVersion: cilium.io/v2
            kind: CiliumClusterwideNetworkPolicy
            metadata:
              name: ambient-mesh-generic-authorization
            spec:
              description: "Generic symmetrical allow for all Ambient mesh namespaces"
              endpointSelector:
                matchExpressions:
                  - key: "k8s.io.cilium.k8s.namespace.labels.istio.io/dataplane-mode"
                    operator: In
                    values: ["ambient"]
              ingress:
                - fromEntities:
                  - all
                  toPorts:
                  - ports:
                    - port: "15008"
                      protocol: TCP
              egress:
                - toEntities:
                  - all
                  toPorts:
                  - ports:
                    - port: "15008"
                      protocol: TCP

  destination:
    name: {{ .Values.global.cluster }}
    namespace: platform-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

{{- end }}
