groups:
  - name: gitlab-backup.rules
    rules:
      - alert: GitlabBackupIncomplete
        expr: '(sum by(namespace, job_name) (kube_job_spec_completions{job_name=~"gitlab-backup.*"}) unless sum by(namespace, job_name) (kube_job_complete == 1)) unless sum by(namespace, job_name) (kube_job_failed == 1)'
        for: 48h
        labels:
          severity: P3-Minor
          scope: namespace
        annotations:
          message: 'Job {{ $$labels.namespace }}/{{ $$labels.job_name }} is taking more than 48 hours to complete.'
