apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: argocd
  labels:
    {{- include "argocd-foundation.labels" $ | nindent 4 }}
  finalizers:
    - argoproj.io/finalizer
spec:

  image: {{ regexReplaceAll "//+" (printf "%s/%s/%s" .Values.argocdInstance.imageRegistry.host .Values.argocdInstance.imageRegistry.repository .Values.argocdInstance.image.name) "/" }}
  version: {{ .Values.argocdInstance.image.version }}

  {{- if .Values.argocdInstance.installationID }}
  installationID: {{ .Values.argocdInstance.installationID }}
  {{- end }}

  ha:
    enabled: false

  grafana:
    enabled: false
    ingress:
      enabled: false
    route:
      enabled: false

  prometheus:
    enabled: false
    ingress:
      enabled: false
    route:
      enabled: false

  tls:
    ca: {}

  nodePlacement:
    nodeSelector: {{ toYaml .Values.argocdInstance.nodeSelector | nindent 6 }}
    tolerations: {{ toYaml .Values.argocdInstance.tolerations | nindent 6 }}

  controller:
    processors: {}
    sharding: {}
    logLevel: {{ .Values.argocdInstance.logLevel }}
    resources:  {{ toYaml .Values.argocdInstance.controller.resources | nindent 6 }}

  applicationSet:
    image: {{ regexReplaceAll "//+" (printf "%s/%s/%s" .Values.argocdInstance.imageRegistry.host .Values.argocdInstance.imageRegistry.repository .Values.argocdInstance.image.name) "/" }}
    version: {{ .Values.argocdInstance.image.version }}
    logLevel: {{ .Values.argocdInstance.logLevel }}
    resources:  {{ toYaml .Values.argocdInstance.applicationSet.resources | nindent 6 }}

  redis:
    image: {{ regexReplaceAll "//+" (printf "%s/%s/%s" .Values.argocdInstance.redis.imageRegistry.host .Values.argocdInstance.redis.imageRegistry.repository .Values.argocdInstance.redis.image.name) "/" }}
    version: {{ .Values.argocdInstance.redis.image.version }}
    resources:  {{ toYaml .Values.argocdInstance.redis.resources | nindent 6 }}

  server:
    autoscale:
      enabled: {{ .Values.argocdInstance.server.autoscale.enabled }}
    grpc:
      ingress:
        enabled: false
    {{- if .Values.argocdInstance.ingressDomain }}
    host: {{ .Values.argocdInstance.ingressDomain }}
    {{- end }}
    ingress:
      enabled: false
    insecure: true
    logLevel: {{ .Values.argocdInstance.logLevel }}
    route:
      enabled: false
    service:
      type: {{ .Values.argocdInstance.server.service.type }}
    resources:  {{ toYaml .Values.argocdInstance.server.resources | nindent 6 }}

  notifications:
    enabled: {{ .Values.argocdInstance.notifications.enabled }}
    logLevel: {{ .Values.argocdInstance.logLevel }}

  repo:
    image: {{ regexReplaceAll "//+" (printf "%s/%s/%s" .Values.argocdInstance.imageRegistry.host .Values.argocdInstance.imageRegistry.repository .Values.argocdInstance.image.name) "/" }}
    version: {{ .Values.argocdInstance.image.version }}
    logLevel: {{ .Values.argocdInstance.logLevel }}
    {{- if .Values.argocdInstance.AADPodIdentity.enabled }}
    labels:
      aadpodidbinding: {{ .Values.argocdInstance.AADPodIdentity.identityName }}
    {{- end }}
    mountsatoken: true
    volumeMounts:
      - mountPath: /etc/ssl/certs/custom.crt
        name: custom-certs
        subPath: custom.crt
    {{- if .Values.argocdInstance.argocdVaultPlugin.enabled }}
    sidecarContainers:
      - command:
          - /var/run/argocd/argocd-cmp-server
        env:
        {{- range $key, $value := .Values.argocdInstance.argocdVaultPlugin.env }}
          - name: {{ $key }}
            value: "{{ $value }}"
        {{- end }}
        image: {{ regexReplaceAll "//+" (printf "%s/%s/%s:%s" .Values.argocdInstance.argocdVaultPlugin.imageRegistry.host .Values.argocdInstance.argocdVaultPlugin.imageRegistry.repository .Values.argocdInstance.argocdVaultPlugin.image.name .Values.argocdInstance.argocdVaultPlugin.image.version) "/" }}
        name: avp
        securityContext:
          runAsNonRoot: true
          runAsUser: 999
        volumeMounts:
          - mountPath: /var/run/argocd
            name: var-files
          - mountPath: /home/argocd/cmp-server/plugins
            name: plugins
          - mountPath: /home/argocd/cmp-server/config/plugin.yaml
            name: {{ .Values.argocdInstance.argocdVaultPlugin.configMapName }}
            subPath: avp.yaml
      - command:
          - /var/run/argocd/argocd-cmp-server
        env:
        {{- range $key, $value := .Values.argocdInstance.argocdVaultPlugin.env }}
          - name: {{ $key }}
            value: "{{ $value }}"
        {{- end }}
        image: {{ regexReplaceAll "//+" (printf "%s/%s/%s:%s" .Values.argocdInstance.argocdVaultPlugin.imageRegistry.host .Values.argocdInstance.argocdVaultPlugin.imageRegistry.repository .Values.argocdInstance.argocdVaultPlugin.image.name .Values.argocdInstance.argocdVaultPlugin.image.version) "/" }}
        name: avp-helm
        securityContext:
          runAsNonRoot: true
          runAsUser: 999
        volumeMounts:
          - mountPath: /var/run/argocd
            name: var-files
          - mountPath: /home/argocd/cmp-server/plugins
            name: plugins
          - mountPath: /home/argocd/cmp-server/config/plugin.yaml
            name: {{ .Values.argocdInstance.argocdVaultPlugin.configMapName }}
            subPath: avp-helm.yaml
    {{- end }}
    volumes:
      {{- if .Values.argocdInstance.argocdVaultPlugin.enabled }}
      - configMap:
          name: {{ .Values.argocdInstance.argocdVaultPlugin.configMapName }}
        name: {{ .Values.argocdInstance.argocdVaultPlugin.configMapName }}
      {{- end }}
      - configMap:
          name: custom-certs
          optional: true
        name: custom-certs
    resources:  {{ toYaml .Values.argocdInstance.repo.resources | nindent 6 }}


  ####### Argo CD Configuration #######


  disableAdmin: {{ .Values.argocdInstance.disableAdmin }}

  extraConfig:
    resource.compareoptions: |
      ignoreAggregatedRoles: true

  {{- if not .Values.argocdInstance.globalProjects | empty }}
    globalProjects: |-
      {{- range .Values.argocdInstance.globalProjects }}
      - labelSelector:
          matchExpressions:
            - key: {{ .labelSelector.key }}
              operator: In
              values:
                - {{ .labelSelector.value }}
        projectName: {{ .projectName }}
      {{- end }}
  {{- end }}

  initialSSHKnownHosts: {}
  kustomizeBuildOptions: --load-restrictor LoadRestrictionsNone --enable-helm

  {{- if and .Values.argocdInstance.oidcAuthSP.tenantID .Values.argocdInstance.oidcAuthSP.clientID .Values.argocdInstance.oidcAuthSP.clientSecret }}
  oidcConfig: |
    name: aurora
    issuer: {{ printf "https://login.microsoftonline.com/%s/v2.0" .Values.argocdInstance.oidcAuthSP.tenantID }}
    clientID: {{ .Values.argocdInstance.oidcAuthSP.clientID }}
    clientSecret: {{ .Values.argocdInstance.oidcAuthSP.clientSecret }}
    requestedIDTokenClaims:
      groups:
        essential: true
    requestedScopes: ["openid","profile","email"]
  {{- end }}

  rbac:
    defaultPolicy: "role:none"
    policy: |
      p, role:none, *, *, */*, deny 
      p, role:org-admin, applications, *, */*, allow
      p, role:org-admin, applicationsets, get, */*, allow
      p, role:org-admin, clusters, get, *, allow
      p, role:org-admin, projects, get, *, allow
      p, role:org-admin, repositories, get, *, allow
      p, role:org-admin, repositories, create, *, allow
      p, role:org-admin, repositories, update, *, allow
      p, role:org-admin, repositories, delete, *, allow
      p, role:org-admin, accounts, get, *, allow
      p, role:org-admin, accounts, update, *, allow
      g, {{ .Values.argocdInstance.adminSecurityGroup | quote }}, role:org-admin
    scopes: '[groups]'


  resourceHealthChecks:
    - group: kiali.io
      kind: Kiali
      check: |
        local health_status = {}
        if obj.status ~= nil then
          if obj.status.conditions ~= nil then
            for i, condition in ipairs(obj.status.conditions) do
              health_status.message = condition.message
              if condition.type == "Successful" and condition.status == "True" then
                health_status.status = "Healthy"
                return health_status
              end
              if condition.type == "Failure" and condition.status == "True" then
                health_status.status = "Degraded"
                return health_status
              end
              if condition.type == "Running" and condition.reason == "Running" then
                health_status.status = "Progressing"
                return health_status
              end
            end
          end
        end
        health_status.status = "Progressing"
        health_status.message = "Waiting for Kiali"
        return health_status
  resourceIgnoreDifferences:
    resourceIdentifiers:
      - group: apiextensions.k8s.io
        kind: CustomResourceDefinition
        customization:
          jqPathExpressions:
            - .spec.conversion?.webhook?.clientConfig.caBundle
            - .spec.preserveUnknownFields
      - group: admissionregistration.k8s.io
        kind: MutatingWebhookConfiguration
        customization:
          jqPathExpressions:
            - .webhooks[]?.clientConfig.caBundle
            - .webhooks[]?.namespaceSelector.matchExpressions[] | select(.key == "control-plane")
            - .webhooks[]?.namespaceSelector.matchExpressions[] | select(.key == "kubernetes.azure.com/managedby")
          managedFieldsManagers:
            - cainjector
            - domain-mapping-webhook
            - webhook
      - group: admissionregistration.k8s.io
        kind: ValidatingWebhookConfiguration
        customization:
          jqPathExpressions:
            - .webhooks[]?.clientConfig.caBundle
            - .webhooks[]?.namespaceSelector.matchExpressions[] | select(.key == "control-plane")
            - .webhooks[]?.namespaceSelector.matchExpressions[] | select(.key == "kubernetes.azure.com/managedby")
          managedFieldsManagers:
            - cainjector
            - domain-mapping-webhook
            - webhook
      - kind: ServiceAccount
        customization:
          managedFieldsManagers:
            - aurora-controller
  resourceExclusions: |
    - apiGroups:
        - cilium.io
      kinds:
        - CiliumIdentity
      clusters:
        - '*'
    - apiGroups:
        - velero.io
      kinds:
        - Backup
      clusters:
        - '*'

  # How Argo CD tracks which Kubernetes resources belong to an Application.
  resourceTrackingMethod: annotation

  # The metadata.label key name where Argo CD injects the app name as a tracking label.
  applicationInstanceLabelKey: {{ .Values.argocdInstance.applicationInstanceLabelKey }}

  # Defines which namespaces to look for applications in
  sourceNamespaces: {{ toYaml .Values.argocdInstance.sourceNamespaces | nindent 4 }}
