{{- if .Values.argocdInstance.AADPodIdentity.enabled }}
---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: {{ .identityName }}
  labels:
    {{- include "argocd-foundation.labels" $ | nindent 4 }}
  annotations:
    aadpodidentity.k8s.io/Behavior: namespaced
spec:
  clientID: {{ .managedIdentity.clientID }}
  resourceID: {{ .managedIdentity.resourceID }}
  type: 0
---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
  name: {{ .identityName }}
  labels:
    {{- include "argocd-foundation.labels" $ | nindent 4 }}
spec:
  azureIdentity: {{ .identityName }}
  selector: {{ .selector | default .identityName }}
{{- end }}
