{{- range $cluster, $saSecrets := .Values.register.clusters }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $cluster }}
  labels:
    argocd.argoproj.io/secret-type: cluster
    {{- include "argocd-foundation.labels" $ | nindent 4 }}
type: Opaque
stringData:
  name: {{ $cluster }}
  server: {{ $saSecrets.server }}
  {{- if and $argocd-k8s-auth ( eq $provider "gcp") }}
  config: |
    {
      "execProviderConfig": {
        "command": "argocd-k8s-auth",
        "args": ["gcp"],
        "apiVersion": "client.authentication.k8s.io/v1beta1"
      },
      "tlsClientConfig": {
        "insecure": false,
        "caData": {{ $saSecrets.caData | quote }}
      }
    }
  {{- else }}
  config: |
    {
      "bearerToken": {{ $saSecrets.token | quote }},
      "tlsClientConfig": {
        "insecure": false,
        "caData": {{ $saSecrets.caData | quote }}
      }
    }
  {{- end }}
{{- end }}
