{{- if .Values.argocdInstance.gateway.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-server-tls
  labels:
    {{- include "argocd-foundation.labels" $ | nindent 4 }}
spec:
  dnsNames:
    - {{ .Values.argocdInstance.gateway.host }}
  issuerRef:
    kind: ClusterIssuer
    name: selfsigned-issuer
    group: cert-manager.io
  commonName: my-self-signed-argocd
  secretName: argocd-server-tls
  privateKey:
    algorithm: ECDSA
    size: 256
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: argocd-gateway
  labels:
    {{- include "argocd-foundation.labels" $ | nindent 4 }}
spec:
  gatewayClassName: {{.Values.argocdInstance.gateway.class | default "gke-l7-rilb"}}
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
    - name: https
      protocol: HTTPS
      port: 443
      tls:
        mode: Terminate
        certificateRefs:
          - group: ''
            kind: Secret
            name: argocd-server-tls
      allowedRoutes:
        namespaces:
          from: Same
  addresses:
    - type: NamedAddress
      value: {{ .Values.argocdInstance.gateway.ipName }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd-gateway-route
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
  - name: argocd-gateway
    sectionName: https
    group: gateway.networking.k8s.io	
    kind: Gateway
  hostnames:
  - {{ .Values.argocdInstance.gateway.host }}
  rules:
  - backendRefs:
    - name: argocd-server
      port: 80
      group: ''
      kind: Service
      weight: 1	
    matches:	
      - path:	
          type: PathPrefix	
          value: /
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd-gateway-redirect
spec:
  parentRefs:
  - name: argocd-gateway
    sectionName: http
    group: gateway.networking.k8s.io	
    kind: Gateway
  hostnames:
  - {{ .Values.argocdInstance.gateway.host }}
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        statusCode: 301
    matches:	
      - path:	
          type: PathPrefix	
          value: /
---
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: argocd-gateway-health-check
spec:
  default:
    checkIntervalSec: 30
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 2
    config:
      type: HTTP
      httpHealthCheck:
        port: 8080
        requestPath: /healthz
  targetRef:
    group: ""
    kind: Service
    name: argocd-server
{{- if eq .Values.argocdInstance.gateway.class "gke-l7-global-external-managed" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: iap-oauth-secret
type: Opaque
stringData:
  # client_id: {{ .Values.argocdInstance.gateway.iapClientID }}
  client_secret: {{ .Values.argocdInstance.gateway.iapClientSecret }}
---
apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: argocd-iap-policy
spec:
  default:
    iap:
      enabled: true
      oauth2ClientSecret:
        name: iap-oauth-secret
  targetRef:
    group: ""
    kind: Service
    name: argocd-server
{{- end }}
{{- end}}