{{- if .Values.argocdInstance.repo.serviceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-repo-server
  {{- with .Values.argocdInstance.repo.serviceAccountAnnotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  labels:
    {{- include "argocd-foundation.labels" $ | nindent 4 }}
{{- end }}