groups:
  - name: gatekeeper.rules
    rules:
      - alert: GatekeeperPolicyViolationsDetected
        annotations:
          message: 'Gatekeeper audit is reporting {{ printf "%.0f" $$value }} deny-level polciy violation(s) on the cluster. This metric is not broken down by constraint. Check Gatekeeper-audit logs to identify the offending resources.'
          value: '{{ printf "%.0f" $$value }}'
        expr: 'sum(gatekeeper_violations{enforcement_action="deny"}) > 0'
        for: 5m
        labels:
          scope: cluster
          severity: P2-Major
          teams_version: v2

      - alert: GatekeeperAuditStale
        annotations:
          message: 'Gatekeeper has not completed an audit run in over 1 hour. Policy Violation Data is now stale, thus GatekeeperPolicyViolationsDetected is not reiable.'
          value: '{{ printf "%.0f" $$value }}'
        expr: 'time() - gatekeeper_audit_last_run_end_time > 3600'
        for: 15m
        labels:
          scope: cluster
          severity: P2-Major
          teams_version: v2

      - alert: GatekeeperMetricsUnavailable
        annotations:
          message: 'Gatekeeper metrics targets have been unavailable for more than 5 minutes.'
          value: '{{ printf "%.0f" $$value }}'
        expr: 'count(up{job="gatekeeper"} == 0) > 0 or absent(up{job="gatekeeper"})'
        for: 5m
        labels:
          scope: cluster
          severity: P2-Major
          teams_version: v2