groups:
  - name: istio-metrics-rules
    rules:
      - alert: IstioHighErrorRate
        annotations:
          summary: 'Istio service has a high error rate'
          message: 'Service {{ $$labels.destination_service_namespace }}/{{ $$labels.destination_service_name }} is returning {{ $$value | humanizePercentage }} HTTP 5xx response via Istio Ingress'
        # calculate the 5xx ratio compare to normal HTTP request
        label_replace(
          (
            (
              sum by (destination_service_namespace, destination_service_name) (
                rate(
                  istio_requests_total{
                    reporter="source",
                    namespace="ingress-general-system",
                    response_code=~"5.."
                  }[5m]
                )
              )
              /
              sum by (destination_service_namespace, destination_service_name) (
                rate(
                  istio_requests_total{
                    reporter="source",
                    namespace="ingress-general-system"
                  }[5m]
                )
              )
            ) > 0.05
            # Only alert when the request frequency is greater than 1/sec
            and on (destination_service_namespace, destination_service_name) (
              rate(
                istio_requests_total{
                  reporter="source",
                  namespace="ingress-general-system"
                }[5m]
              )
            ) > 1
          ),
          "namespace",
          "$1",
          "destination_service_namespace",
          "(.+)"
        )
        for: 10m
        labels:
          scope: namespace
          severity: P1-Critical
          teams_version: v2
