{{- if .Values.argocdProject.enabled }}

apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ $.Release.Name }}
  labels:
    argocd.argoproj.io/project-inherit: global
    project.ssc-spc.gc.ca/sync: argo
spec:

  # Which namespaces can use this AppProject 
  sourceNamespaces:
    - {{ $.Release.Name }}

  # Which repositories are allowed
  sourceRepos: {{ toYaml .Values.argocdProject.sourceRepos }}

  # The clusters where the tenant's applications are hosted
  destinations:
    - server: "*"
      namespace: {{ $.Release.Name }}

  roles:
    # Role for "admins" - full control including delete/force-sync
    - name: admin-role
      description: Admin access for applications
      groups: {{ toYaml (default .Values.rbac.groups .Values.argocdProject.adminGroups) | nindent 6 }}
      policies:
        # Full control over applications in this project
        - p, proj:{{ $.Release.Name }}:admin-role, applications, *, {{ $.Release.Name }}/*, allow
        - p, proj:{{ $.Release.Name }}:admin-role, applicationsets, *, {{ $.Release.Name }}/*, allow
        - p, proj:{{ $.Release.Name }}:admin-role, logs, *, {{ $.Release.Name }}/*, allow
        - p, proj:{{ $.Release.Name }}:admin-role, exec, *, {{ $.Release.Name }}/*, allow

    {{- if .Values.argocdProject.developerGroups }}
    # Role for "developers" - can view and sync, but not delete Applications
    - name: developer-role
      description: Developer access applications
      groups: {{ toYaml .Values.argocdProject.developerGroups | nindent 6 }}
      policies:
        # Allow read-only access to all applications in this project
        - p, proj:{{ $.Release.Name }}:developer-role, applications, get, {{ $.Release.Name }}/*, allow
        # Allow sync (manual or automatic), but deny delete and terminate/force-sync
        - p, proj:{{ $.Release.Name }}:developer-role, applications, sync, {{ $.Release.Name }}/*, allow
        - p, proj:{{ $.Release.Name }}:developer-role, applications, action/terminate, {{ $.Release.Name }}/*, deny
        # Allow viewing pod logs & exec into pods
        - p, proj:{{ $.Release.Name }}:admin-role, logs, *, {{ $.Release.Name }}/*, allow
        - p, proj:{{ $.Release.Name }}:admin-role, exec, *, {{ $.Release.Name }}/*, allow
    {{- end }}

{{- end }}
