apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ $.Release.Name }}
  labels:
    argocd.argoproj.io/project-inherit: global
  # This metadata is for Argo CD's internal use and grouping
spec:
  # Only allow applications to sync from Acme Corp's official GitOps repository.
  # This prevents them from deploying arbitrary code from unapproved repos.
  sourceRepos: {{ toYaml .Values.argoCD.sourceRepos }}

  # The clusters where the tenant's applications are hosted
  destinations:
  - server: "*"
    namespace: {{ $.Release.Name }}
  
  # Blacklist ALL cluster-scoped resources (e.g., ClusterRole, PersistentVolume) 
  # by setting a general whitelist and then blacklisting high-risk kinds explicitly.
  clusterResourceBlacklist:
  - group: '*'
    kind: '*'

  # Only allow the tenant to manage common resources (Deployments, Services, etc.)
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*' # Allow all namespace-scoped resources, as long as the destination is their namespace

  roles:
  # # Role for "developers" - can view and sync, but not delete Applications
  # - name: developer-role
  #   description: Developer access for Acme Corp applications
  #   # Bind this role to an OIDC group from your SSO provider (e.g., Okta, Keycloak)
  #   groups:
  #   - 'acme-corp-developers'
  #   # Define the RBAC policies for this role
  #   policies:
  #   # Allow read-only access to all applications in this project
  #   - p, proj:acme-corp:developer-role, applications, get, acme-corp/*, allow
  #   # Allow sync (manual or automatic), but deny delete and terminate/force-sync
  #   - p, proj:acme-corp:developer-role, applications, sync, acme-corp/*, allow
  #   - p, proj:acme-corp:developer-role, applications, action/terminate, acme-corp/*, deny

  # Role for "admins" - full control including delete/force-sync
  - name: admin-role
    description: Admin access for applications
    groups: {{ toYaml .Values.rbac.groups }}
    policies:
    # Full control over applications in this project
    - p, proj:acme-corp:admin-role, applications, *, {{ $.Release.Name }}/*, allow
    - p, proj:acme-corp:admin-role, applicationsets, *, {{ $.Release.Name }}/*, allow