{{ if .Values.components.secretsStoreCSIDriver.enabled -}}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ .Values.global.cluster }}-secrets-store-csi-driver"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.global.project }}
  source:
    chart: {{ default "secrets-store-csi-driver" .Values.components.secretsStoreCSIDriver.helm.chart }}
    {{- if .Values.components.secretsStoreCSIDriver.helm.repository }}
    repoURL: {{ .Values.components.secretsStoreCSIDriver.helm.repository }}
    {{- else }}
    repoURL: {{ default "https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts" .Values.global.helm.repository }}
    {{- end }}
    targetRevision: {{ default "1.5.4" .Values.components.secretsStoreCSIDriver.targetRevision }}
    helm:
      releaseName: secrets-store-csi-driver
      values: |-
        linux:
          enabled: true

          image: {{- default "{}" (include "driver.image" .) | nindent 12 }}

          driver:
            {{ if .Values.components.secretsStoreCSIDriver.resources -}}
            resources: {{ toYaml .Values.components.secretsStoreCSIDriver.resources | nindent 14 }}
            {{- end }}


          crds:
            enabled: true
            image: {{- default "{}" (include "crds.image" .) | nindent 14 }}

          registrarImage: {{- default "{}" (include "registrar.image" .) | nindent 12 }}
            
          priorityClassName: {{ .Values.components.secretsStoreCSIDriver.priorityClassName }}


          {{ if .Values.components.secretsStoreCSIDriver.tolerations -}}
          tolerations: {{ toYaml .Values.components.secretsStoreCSIDriver.tolerations | nindent 12 }}
          {{- end }}

        windows:
          # not supported at the moment
          enabled: false

  destination:
    name: {{ .Values.global.cluster }}
    namespace: secrets-store-csi-driver-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

{{- end }}
