name: Render and Validate Helm Template

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  helm-render:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Helm
        uses: actions/setup-go@v5
        with:
          go-version: '1.19'
      - run: |
          curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Install kubeconform
        run: |
          curl -LO https://github.com/yannh/kubeconform/releases/download/v0.6.0/kubeconform-linux-amd64.tar.gz
          tar -xzf kubeconform-linux-amd64.tar.gz kubeconform
          sudo mv kubeconform /usr/local/bin/

      - name: Render Helm template
        run: |
          helm template aurora stable/aurora-platform \
            --namespace platform-management-system \
            --values config/config.yaml \
            --include-crds > rendered.yaml

      - name: Validate rendered YAML with kubeconform
        run: |
          kubeconform -strict -ignore-missing-schemas -summary rendered.yaml

      - name: Upload rendered.yaml as artifact
        uses: actions/upload-artifact@v4
        with:
          name: rendered-template
          path: rendered.yaml